apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-eventing-controller
  labels:
    eventing.knative.dev/release: devel
rules:
  - apiGroups:
      - eventing.knative.dev
    resources:
      - triggers
      - triggers/status
      - brokers
      - brokers/status
    verbs:
      - watch
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - watch
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
