apiVersion: eventing.knative.dev/v1beta1
kind: Broker
metadata:
  name: my-broker
  namespace: jwatch
spec:
  # Configuration specific to this broker.
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing

